# Generated by Django 5.0.4 on 2024-04-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_model_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brend', 'verbose_name_plural': 'Brandlar'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Modellar'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Brend'),
        ),
        migrations.AlterField(
            model_name='model',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brand', verbose_name='Brend'),
        ),
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.TextField(verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='model',
            name='mileage',
            field=models.IntegerField(verbose_name='Yurgan'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='model',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='model',
            name='price',
            field=models.IntegerField(verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='model',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="E'lon qo'yilgan sana"),
        ),
        migrations.AlterField(
            model_name='model',
            name='year',
            field=models.IntegerField(verbose_name='Yil'),
        ),
    ]
