# Generated by Django 5.0.4 on 2024-04-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_brand_options_alter_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasm'),
        ),
    ]
