# Generated by Django 5.0.4 on 2024-04-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_model_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['-id'], 'verbose_name': 'Model', 'verbose_name_plural': 'Modellar'},
        ),
        migrations.AddField(
            model_name='model',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
