# Generated by Django 5.0.4 on 2024-04-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_model_options_model_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/', verbose_name='Rasm'),
        ),
    ]
