# Generated by Django 5.0.4 on 2024-04-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_model_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasm'),
        ),
    ]
